### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by CHSLAM** [SlamMate/CDS-SLAM-Semantic-mapping-in-dynamic-environment#1]
我想问一下这个怎么编译运行啊，readme里面没有写

**Comment by SlamMate** [comment]
和ORBSLAM3的编译过程一样，可以参考下面新添加的ORBSLAM3的链接哦。
---------------------
This project is the same as the compilation process of ORB-SLAM3. Please refer to the newly added ORB-SLAM3 link below.
