### ISSUE TITLE
结果

### ISSUE THREAD

**Issue by zhoushuailin** [SlamMate/CDS-SLAM-Semantic-mapping-in-dynamic-environment#2]
请问这个仓库的代码是能运行出结果的嘛，只是效果不好？

**Comment by SlamMate** [comment]
是的，是语义颜色渲染的效果不太好。但是定位精度很棒。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 下午3:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [SlamMate/CDS-SLAM-Semantic-mapping-in-dynamic-environment] 结果 (Issue #2)





 
请问这个仓库的代码是能运行出结果的嘛，只是效果不好？
