### ISSUE TITLE
build.sh遇到問題

### ISSUE THREAD

**Issue by luyihsien** [SlamMate/CDS-SLAM-Semantic-mapping-in-dynamic-environment#4]
pointcloudmapping.cc:739:10: error: ‘Config’ is not a member of ‘APC’
     APC::Config config;
pointcloudmapping.cc:740:5: error: ‘config’ was not declared in this scope
     config.noise_threshold = 0.01; // 1cm
出現這兩個錯誤 打開源碼看發現真的沒有定義也不是成員 想詢問怎麼修正？謝謝

**Comment by SlamMate** [comment]
现在没有问题了，之前是两三个项目拼在一起。。。然后我维护了一下。。。抱歉。
